using LogMicroservice.Repositories.Entities;
using LogMicroservice.Repositories.Interfaces;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace LogMicroservice.Repositories
{
    /// <summary>
    /// Repository for all Error methods
    /// </summary>
    public class ErrorRepository : ControllerBase, IErrorRepository
    {
        /// <summary>
        /// Handles global errors generated by the app
        /// </summary>
        /// <returns>An IActionResult with an Error object</returns>
        IActionResult IErrorRepository.HandleErrors()
        {
            var contextException = HttpContext.Features.Get<IExceptionHandlerFeature>();

            return BadRequest(new ApiError
            {
                StatusCode = 400,
                Errors = new List<ErrorDetail> {
                    new ErrorDetail {
                        Title = contextException.Error.Source,
                        Message = contextException.Error.Message
                    }
                }
            });
        }
    }
}
