using Microsoft.AspNetCore.Mvc;

namespace LogMicroservice.Repositories.Interfaces
{
    /// <summary>
    /// Interface for Error Repository 
    /// </summary>
    public interface IErrorRepository
    {
        /// <summary>
        /// Handles global errors generated by the app
        /// </summary>
        /// <returns>An IActionResult with an Error object</returns>
        IActionResult HandleErrors();
    }
}
